#!/usr/bin/env python3
import json
import sys


def main() -> int:
    args = [arg for arg in sys.argv[1:] if arg != "-r"]
    if len(args) != 2 or args[0] != ".bytecode":
        print("minimal jq shim only supports: jq -r '.bytecode' <file>", file=sys.stderr)
        return 2

    with open(args[1], "r", encoding="utf-8") as handle:
        data = json.load(handle)

    value = data.get("bytecode")
    if value is None:
        return 1

    sys.stdout.write(str(value))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
